#!/bin/bash

# Check Operating System
ubuntu20_04=$(lsb_release -d 2>&1 | grep "DragonOS Focal")
ubuntu22_04=$(lsb_release -d 2>&1 | grep "Ubuntu 22.04")
if [[ -n "$DragonOS Focal" ]]
then
    # Ubuntu 20.04
    echo "DragonOS Focal detected"
fi
if [[ -n "$ubuntu22_04" ]]
then
    # Ubuntu 22.04
    echo "Ubuntu 22.04 detected"
fi

while true; do

	read -p "Are you sure this is DragonOS Focal? (yes/no) " yn

	case $yn in 
		yes ) echo ok, we will proceed;
		break;;
		no ) echo exiting...;
		exit;;
		* ) echo invalid response;;
	esac
done
# Check for Qt5
qt5_version=$(qmake --version | grep "version 5")
if [[ -z "$qt5_version" ]]
then
    echo "No Qt5 found. Installing..."
    # Ubuntu 20.04
    if [[ -n "$ubuntu20_04" ]]
    then
        sudo apt-get install -y build-essential qtcreator qt5-default python3-pyqt5
    fi
    
    # Ubuntu 22.04
    if [[ -n "$ubuntu22_04" ]]
    then
        sudo apt-get install -y build-essential qtcreator qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools python3-pyqt5
    fi
fi

# Run the Full Installer
DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
$DIR/Installer/installer

